require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LearningPathsController do

  # This should return the minimal set of attributes required to create a valid
  # LearningPath. As you add validations to LearningPath, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LearningPathsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all learning_paths as @learning_paths" do
      learning_path = LearningPath.create! valid_attributes
      get :index, {}, valid_session
      assigns(:learning_paths).should eq([learning_path])
    end
  end

  describe "GET show" do
    it "assigns the requested learning_path as @learning_path" do
      learning_path = LearningPath.create! valid_attributes
      get :show, {:id => learning_path.to_param}, valid_session
      assigns(:learning_path).should eq(learning_path)
    end
  end

  describe "GET new" do
    it "assigns a new learning_path as @learning_path" do
      get :new, {}, valid_session
      assigns(:learning_path).should be_a_new(LearningPath)
    end
  end

  describe "GET edit" do
    it "assigns the requested learning_path as @learning_path" do
      learning_path = LearningPath.create! valid_attributes
      get :edit, {:id => learning_path.to_param}, valid_session
      assigns(:learning_path).should eq(learning_path)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LearningPath" do
        expect {
          post :create, {:learning_path => valid_attributes}, valid_session
        }.to change(LearningPath, :count).by(1)
      end

      it "assigns a newly created learning_path as @learning_path" do
        post :create, {:learning_path => valid_attributes}, valid_session
        assigns(:learning_path).should be_a(LearningPath)
        assigns(:learning_path).should be_persisted
      end

      it "redirects to the created learning_path" do
        post :create, {:learning_path => valid_attributes}, valid_session
        response.should redirect_to(LearningPath.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved learning_path as @learning_path" do
        # Trigger the behavior that occurs when invalid params are submitted
        LearningPath.any_instance.stub(:save).and_return(false)
        post :create, {:learning_path => { "name" => "invalid value" }}, valid_session
        assigns(:learning_path).should be_a_new(LearningPath)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LearningPath.any_instance.stub(:save).and_return(false)
        post :create, {:learning_path => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested learning_path" do
        learning_path = LearningPath.create! valid_attributes
        # Assuming there are no other learning_paths in the database, this
        # specifies that the LearningPath created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LearningPath.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => learning_path.to_param, :learning_path => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested learning_path as @learning_path" do
        learning_path = LearningPath.create! valid_attributes
        put :update, {:id => learning_path.to_param, :learning_path => valid_attributes}, valid_session
        assigns(:learning_path).should eq(learning_path)
      end

      it "redirects to the learning_path" do
        learning_path = LearningPath.create! valid_attributes
        put :update, {:id => learning_path.to_param, :learning_path => valid_attributes}, valid_session
        response.should redirect_to(learning_path)
      end
    end

    describe "with invalid params" do
      it "assigns the learning_path as @learning_path" do
        learning_path = LearningPath.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LearningPath.any_instance.stub(:save).and_return(false)
        put :update, {:id => learning_path.to_param, :learning_path => { "name" => "invalid value" }}, valid_session
        assigns(:learning_path).should eq(learning_path)
      end

      it "re-renders the 'edit' template" do
        learning_path = LearningPath.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LearningPath.any_instance.stub(:save).and_return(false)
        put :update, {:id => learning_path.to_param, :learning_path => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested learning_path" do
      learning_path = LearningPath.create! valid_attributes
      expect {
        delete :destroy, {:id => learning_path.to_param}, valid_session
      }.to change(LearningPath, :count).by(-1)
    end

    it "redirects to the learning_paths list" do
      learning_path = LearningPath.create! valid_attributes
      delete :destroy, {:id => learning_path.to_param}, valid_session
      response.should redirect_to(learning_paths_url)
    end
  end

end
